spring:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:starwars
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
    websocket:
      path: /graphql/ws
    jpa:
      query:
        name: Query
        description: GraphQL Jpa Query Starwars Schema Example
        enabled: true
