spring:
  application:
    name: graphql-jpa-query-getting-started
  jpa:
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  graphql:
    graphiql:
      enabled: true
    jpa:
      query:
        enable-relay: true
server:
  port: 8080
