version: "3.2"
services:
    gpaphql-jpa-query-example:
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - 8080:8080
        image: introproventures/graphql-jpa-query-example:latest
        networks:
            - application
networks:
    application:
        driver: overlay
