spring:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    open-in-view: false
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:starwars

  graphql:
    jpa:
      query:
        name: GraphQLJpaQueryStarwars
        description: GraphQL Jpa Query Starwars Schema Example
        enabled: true
